using System;
using System.Collections.Generic;
namespace ClashOfCities.Core
{
    [Serializable] public class GameData { public CityDefinition[] cities; public AvatarDefinition[] avatars; public AbilityDefinition[] abilities; public ClimateEventDefinition[] environments; public BalanceConfig balance; }
    [Serializable] public class CityDefinition { public string id, name; public bool isDemoData=true; public double greenScore, waterScore, heatProtectionScore, sealingScore, resilienceScore, heatRiskScore; }
    [Serializable] public class AvatarDefinition { public string id, displayName, cityId, combatClass, description, visualPrefabReference, connectionType, connectionDescription; public double baseMovementSpeed=3, attackRange=2; public string attackStyle="Projectile"; public string[] abilityIds; }
    [Serializable] public class AbilityDefinition { public string id, name, effectType, climateScaling, statusEffect; public double cooldown, baseDamage, range, areaOfEffect, energyCost, castTime, duration=3, magnitude=0.2; public string description; public string onHitSelfEffect, onHitTargetEffect; public double onHitSelfDuration=3,onHitSelfMagnitude=.25,onHitTargetDuration=1,onHitTargetMagnitude=.25; public string delivery="Projectile"; public double projectileSpeed=0, projectileRadius=0, telegraphSeconds=.65, zoneDuration=2, coneDegrees=100, dashDistance=4; public bool isUltimate; }
    [Serializable] public class ClimateEventDefinition { public string id, name; public double greenWeight=.2, waterWeight=.15, heatProtectionWeight=.25, unsealedWeight=.1, resilienceWeight=.2, lowHeatRiskWeight=.1; public double heatDamagePerSecond; }
    [Serializable] public class BalanceConfig { public string version="demo-5"; public double controlImmunitySeconds=2,maxStunSeconds=1.4,maxRootSeconds=1.8; public double backpedalMultiplier=.72, ringStartSeconds=45, ringEndSeconds=120, ringFinalRadius=6.5, ringDamagePerSecond=8; public double tickSeconds=.05, maxDuration=180, baseHealth=500, healthPerPower=5, baseAttack=12, attackPerPower=.3, baseDefense=5, defensePerGreen=.3, defensePerResilience=.2, baseEnergy=80, energyPerWater=.5, baseEnergyRegen=4, energyRegenPerWater=.05, healthRegenPerGreen=.025, staminaPerUnsealed=.005, cooldownReductionPerResilience=.003, basicAttackInterval=1.2, basicEnergyGain=5, criticalChance=.08, criticalMultiplier=1.5, dodgeChance=.03, damageVariance=.05, defenseConstant=100, arenaHalfSize=12, ultimateUnlockSeconds=8, abilityRecoverySeconds=.3, healThreshold=.8, abilityScalingBase=.5, dodgeDuration=.28, dodgeCooldown=3, dodgeEnergyCost=18, dodgeSpeedMultiplier=2.8, strafeSpeedMultiplier=.45, retreatSpeedMultiplier=.8, retreatDuration=.55, minimumFighterDistance=1.1, cpuPreferredRangeRatio=.83, projectileSpeed=9, projectileRadius=.24, fighterHitRadius=.48, chargeDuration=1.8, chargeMinSeconds=.25, cpuReactionSeconds=.22; }
    [Serializable] public class MatchConfig { public string cityAId, avatarAId, cityBId, avatarBId, climateEventId, balanceVersion; public int seed; public MatchMode mode; public CpuDifficulty difficulty; }
    public class CombatStats { public double ClimatePower, MaxHealth, AttackPower, Defense, Energy, EnergyRegeneration, HealthRegeneration, HeatResistance, MovementStamina, CooldownModifier; }
    public enum CombatState { Idle, MoveToTarget, BasicAttack, UseAbility, Recover, Defend, Dead, Retreat, Strafe, Dodge }
    public enum CpuDifficulty { Normal, Easy, Hard }
    public enum MatchMode { CpuVsCpu, PlayerVsCpu, PlayerVsPlayer }
    [Serializable] public struct FighterInput { public double moveX, moveZ; public bool basicAttack, skill1, skill2, ultimate, dodge; }
    [Serializable] public class InputFrame { public int tick; public FighterInput a, b; }
    public class StatusEffect { public string Type; public double Remaining, Magnitude; public int Source; }
    public class FighterState { public int Index; public CityDefinition City; public AvatarDefinition Avatar; public CombatStats Stats; public double Health, Energy, Shield, X, Z, RecoveryRemaining, BasicAttackCooldown, CastRemaining; public string CastingAbilityId; public CombatState State; public Dictionary<string,double> Cooldowns=new Dictionary<string,double>(); public List<StatusEffect> Effects=new List<StatusEffect>(); public double DamageDealt, HealingDone, VelocityX, VelocityZ, DodgeRemaining, DodgeCooldown, DodgeX, DodgeZ, TacticalRetreatRemaining; public double ControlImmunityRemaining,ChargeElapsed; public double Charge, AimX, AimZ, CastTargetX, CastTargetZ; public bool IsCharging; public string ChargingAbilityId; public int BasicAttacks, AbilitiesUsed; public Dictionary<string,int> AbilityUsage=new Dictionary<string,int>(); }
    [Serializable] public class FighterResult { public string cityId, avatarId; public double remainingHealth, damageDealt, healingDone; public int basicAttacks, abilitiesUsed; public string[] abilityIds; public int[] abilityCounts; }
    [Serializable] public class MatchResult { public MatchConfig config; public string winnerCityId, outcome; public int winnerIndex; public double duration; public FighterResult fighterA, fighterB; public InputFrame[] inputs; }
    public class ProjectileState { public int Id,Source,Target; public string AbilityId; public double X,Z,DirectionX,DirectionZ,Speed,Radius,Remaining,Power,Age; public bool IsUltimate; }
    public class TerrainZone { public int Id; public string Kind; public double X,Z,Radius; }
    public class ArenaObstacle { public int Id; public double X,Z,Radius,Height; }
    public class AreaState { public int Id,Source,Target; public string AbilityId; public double X,Z,Radius,WarningRemaining,Remaining,Power; public double PulseElapsed; public bool Hit; }
    public class BattleEvent { public string Type, AbilityId, Delivery; public int Source, Target, ProjectileId; public double Amount,X,Z,DirectionX,DirectionZ,Radius; }
}
